apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: cicd-demo

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: 084400305795.dkr.ecr.us-east-1.amazonaws.com/frontend:v2

        imagePullPolicy: Always

        ports:
        - containerPort: 5001